name: Periodic Health Check

on:
  schedule:
    - cron: "0 */24 * * *"   # 1 vez cada 24 horas
  workflow_dispatch:          # por si quieres ejecutarlo manualmente

jobs:
  check-health:
    runs-on: ubuntu-latest
    
    steps:
      - name: Health check â€” backend Render
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-backend-xzyw.onrender.com/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s